sonar.projectKey=fromzero-framework
sonar.projectName=Project - From Zero Framework
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=.next/**,node_modules/**,coverage/**,playwright-report/**,test-results/**,docs/**,.codex/**
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.spec.ts
